house_pricing:
  train_dataset: ~/w/AI/practicum_1/kaggle_house_prices/train.csv
  test_dataset: ~/w/AI/practicum_1/kaggle_house_prices/test.csv
classification:
  wdbc: D:\data\spbu_ai_fundamentals/classification/data.csv
  mushrooms: D:\data\spbu_ai_fundamentals/classification/mushrooms.csv
clustering:
  flowcytometry: D:\data\spbu_ai_fundamentals/flow_cytometry
